<MsgPopUp>:
        GridLayout:
                cols: 1
                rows: 2
                size: root.size
                pos: root.pos
                GridLayout:
                        id: msgGrid
                        rows: 2
                        cols: 1
                        padding: 10
                        spacing: 10

<CfmPopUp>:
        GridLayout:
                cols: 1
                rows: 1
                size: root.size
                pos: root.pos
                GridLayout:
                        id: cfmGrid
                        rows: 2
                        cols: 1
                        padding: 10
                        spacing: 10